# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
name: Patrick Lange
email: mail@langep.com
description: > # this means to ignore newlines until "url:"
  Personal website and 'speech-controlled' blog.

url: "https://www.langep.com" # the base hostname & protocol for your site
baseurl: # the subpath of your site, e.g. /blog/
last_updated: 2019-03-10 # leave blank if you don't want to display last updated

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------
github_username: langep # put your github username
twitter_username: pl_in_sf # put your twitter username
linkedin_username: langep # put your linkedin username
scholar_authorid: 6TxeqJwAAAAJ # put your google scholar author id
contact_note: >
  The best way to reach me is via email.

google_analytics: UA-86140203-1 # out your google-analytics code

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------
blog_name: speech-controlled
blog_description: all things speech

# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

text:
  pagination:
    newer: 'Newer'
    older: 'Older'

# Comments
disqus_shortname: langep # put your disqus shortname

# Optional features
show_social_icons:  false
enable_anchorjs:    false
enable_katex:       true

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/

news_limit: 5

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
highlighter: pygments

# Includes
include: ['_pages']

# Plugins
plugins:
    - jekyll-paginate
    - jekyll/scholar
    - jemoji
    - jekyll-sitemap

# Jekyll-Scholar
scholar:

  last_name: Lange

  repository: /assets/pdf/

  style: apa
  locale: en

  sort_by: year
  order: descending

  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
katex_version: "0.7.1"
anchorjs_version: "3.2.2"
